@MedPoint.Main.Web_HostAddress = http://localhost:5067

GET {{MedPoint.Main.Web_HostAddress}}/Availability/
Accept: application/json

###
POST {{MedPoint.Main.Web_HostAddress}}/Availability/
Content-Type: application/json

{
  "id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "time": "2025-01-18T09:53:35.735Z",
  "doctorId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "doctorName": "string",
  "isReserved": true,
  "cost": 0
}
